# SPAwn Example Configuration

# Globus configuration
globus:
  # Globus Auth token with search.ingest scope
  # auth_token: "your-globus-auth-token"

  # Globus Search index UUID
  search_index: "your-search-index-uuid"

  # List of Globus Auth identities that can see entries
  visible_to: ["public"]

  # Globus Compute endpoint ID
  # compute_endpoint_id: "your-compute-endpoint-id"

  # Globus Flow ID (if you have an existing flow)
  # flow_id: "your-flow-id"

  # Globus Auth client ID and secret (for creating flows)
  # client_id: "your-client-id"
  # client_secret: "your-client-secret"

# Output directory for generated files
output:
  dir: "./output"

# Crawler configuration
crawler:
  # Time in seconds to wait between file operations (to reduce system load)
  polling_rate: 0.01

  # Whether to ignore directories starting with a dot (e.g., .git, .vscode)
  ignore_dot_dirs: true

  # Regex patterns to exclude from crawling
  exclude_regex:
    - ".*\\.tmp$"          # Temporary files
    - ".*\\.log$"          # Log files
    - ".*\\.bak$"          # Backup files
    - ".*~$"               # Backup files with tilde
    - "node_modules/.*"    # Node.js modules
    - "__pycache__/.*"     # Python cache

  # Regex patterns to include in crawling (only these files will be processed)
  include_regex:
    - ".*\\.py$"           # Python files
    - ".*\\.md$"           # Markdown files
    - ".*\\.txt$"          # Text files
    - ".*\\.json$"         # JSON files
    - ".*\\.ya?ml$"        # YAML files
    - ".*\\.csv$"          # CSV files
    - ".*\\.pdf$"          # PDF files
    - ".*\\.(jpe?g|png|gif|svg)$"  # Image files

  # Plugins configuration
  plugins:
    text:
      enabled: true
      max_content_length: 100000
    image:
      enabled: true
    pdf:
      enabled: true

# Metadata configuration
metadata:
  # Whether to save metadata as JSON files
  save_json: true

  # Directory to save JSON metadata files in
  json_dir: "./metadata_json"

# GitHub configuration
github:
  # GitHub personal access token (or set GITHUB_TOKEN environment variable)
  # Required for creating repositories
  # token: "your-github-token"

  # GitHub username (or set GITHUB_USERNAME environment variable)
  # username: "your-github-username"

# Portal configuration
portal:
  name: "My Data Portal"
  description: "Search and browse indexed data"
  theme: "default"
  facets:
    - field: "extension"
      label: "File Type"
    - field: "mime_type"
      label: "MIME Type"
    - field: "language"
      label: "Language"
  results_per_page: 20
